---
- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - glances
    - python-bottle

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Set selinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Copy glancesweb service config file
  template:
    src: glancesweb.service
    dest: /usr/lib/systemd/system/glancesweb.service

- name: start glances service
  service:
    name: glancesweb.service
    state: started
    enabled: true


